### PR TITLE
Add support to Xblock handlers and general improvements.

### PR DESCRIPTION
**Pull request by Squirrel18**
## Description:

This PR removes the rest folder, that contains a url and endpoints definitions, in order to use Xblock.handler instead.

Also adds support for Jinja templates, and fixes default Jupyter notebook css.

## Test:

- Clone this repo inside src folder.
- Checkout to this branch.
- Inside of studio/lms shell run: pip install -e /edx/src/jupyter-viewer-xblock/
- Go to advanced settings -> Advanced Module List -> add "xblock_jupyter_viewer"
- Create a new unit with Jupyter Xblock viewer.
- Set up the notebook and images url in edit settings of the Xblock. E.G. [Example notebooks](https://github.com/engineersCode/EngComp1_offtheground/tree/1a7251f87f2da55699ac892c7eeb9d81c5c09acd/notebooks_en)
- Testing that the notebook looks correctly in Studio and LMS.

## Future work:

- Improve the preprocessors and postprocessor.
- Run Pylint in this Xblock.

## Reviewers:

- [ ] @diegomillan 
- [ ] @felipemontoya

### CODE REVIEW

**Comment by felipemontoya** [comment]
@Squirrel18 please let me know when this is ready to be reviewed.

**Comment by Squirrel18** [comment]
@felipemontoya @diegomillan PR updated, please let me know if you have any question.

**Review by diegomillan — APPROVED** [review]
I have tested it using a public notebook at anaconda cloud. Everything works.

**Comment by diegomillan** [comment]
Once we merge this, we must update our requirements at edunext-platform

@Squirrel18 @felipemontoya @jfavellar90

**Comment by diegomillan** [comment]
This is ready for review @felipemontoya

**Comment by felipemontoya** [comment]
I went through the code and don't see anything else to add.
Just one question, do we need to remove the view that was being included in the original instructions? or do we leave it here even though it should not be called?

**Review by felipemontoya — APPROVED** [review]
I'll leave my approve here, but please consider the part about the view before merging

**Comment by Squirrel18** [comment]
@felipemontoya I removed the view since the only method defined inside we'll not be used anymore, and anything related to the rest folder is not used. It is neccesary to update the readme file in this PR or other related to it?

**Comment by felipemontoya** [comment]
@Squirrel18 no need to update the PR, I think I just did not notice it was removed already. I focused more on the adding changes.
This is ready to merge then

**Comment by Squirrel18** [comment]
@felipemontoya @diegomillan Are we going to make a release version after this PR will be merged.

**Comment by diegomillan** [comment]
Yes @Squirrel18, also we have to change the reference to our fork in edx-platform

**Pull request merged**
